pages:
  stage: deploy
  tags:
    - gitlab-runner  # 必須跟截圖中的藍色標籤一模一樣
  script:
    - mkdir public
    - cp -r * public/
  artifacts:
    paths:
      - public
  only:
    - main  # 確認你的分支是 main 還是 master
